### PR TITLE
Add riscv64 images

### PR DESCRIPTION
**Pull request by kit-ty-kate**

### CODE REVIEW

**Review by lafin — APPROVED** [review]

**Review by lafin — COMMENTED** [review]
feat: sort of lines

**Review by lafin — APPROVED** [review]

**Comment by kit-ty-kate** [comment]
Hi, thanks for the merge. However there seems to have been a problem during the merge as the commit does not exist (anymore?) in the master branch. Do i have to recreate a PR to merge it again?

**Comment by lafin** [comment]
@kit-ty-kate yes, please recreate pr.
I made a hard reset. after the merge, I saw problems in the pipeline, I need to figure out why this happened. maybe this arch does not exist for all versions of alpine or something.
https://github.com/multiarch/alpine/actions/runs/3939544951/jobs/6739528501

**Comment by kit-ty-kate** [comment]
Actually it looks like alpine does not provide the required files for riscv64 platforms for its stable platforms.
Only `edge` has it. I've asked on IRC and there is no plans for it to go outside of `edge` anytime soon ("whenever we have the proper hardware on hand" type thing)

I'll redo the PR by restricting it to `edge` for now

**Pull request merged**
